project:
  type: website
website:
  title: "Tohubohu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - plans.qmd
      - whereabouts.qmd
      - projects.qmd
      - technical.qmd
      - preparations.qmd
      - about.qmd

format:
  html:
    toc: true
    theme: spacelab
    mermaid:
      theme: neutral



