project:
  type: website

website:
  title: "Tohubohu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - plans.qmd
      - whereabouts.qmd
      - projects.qmd
      - technical.qmd
      - preparations.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



